# Generated by Django 2.2.28 on 2024-05-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('director', models.CharField(max_length=128, null=True)),
                ('release_date', models.DateField(null=True)),
                ('cover_art', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
