# Generated by Django 5.0.6 on 2024-05-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_savedmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saved_movies',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='film.savedmovie'),
        ),
    ]
